//Faça um algoritmo para calcular e mostrar a tabuada do N onde N é um número informado pelo usuário.










algoritmo "Tabuada N"

var
   contador, resultado:inteiro
   tabuadaN :inteiro
inicio
   escreva ("Informe a tabuada:")
   leia(tabuadaN)
   para contador <- 0 ate 10 faca
      resultado <- tabuadaN*contador
      escreval(tabuadaN, " X ", contador, " = ", resultado)
   fimpara

fimalgoritmo


